### ISSUE TITLE
Eliminate unnecessary composite primary keys

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics-data#1]
Some of our tables have schemas like the following:

```
CREATE TABLE [dbo].[cancellationpolicy](
	[CancellationPolicyID] [int] NOT NULL,
...
CONSTRAINT [PK__cancella__4BAA8CCE7A0806B6] PRIMARY KEY CLUSTERED 
(
	[CancellationPolicyID] ASC,
	[LanguageID] ASC,
	[CountryID] ASC
)
```

This is not strictly necessary. The record ID should be universally unique, and sufficient to establish a foreign key relationship. Composite primary and foreign key relationships make it difficult to run tools like typeorm-model-generator. As such, we shouldn't use this complexity unless necessary, and should remove it from our schema or model it in a different way without composite keys.

**Comment by IagoSRL** [comment]
We should start by analyzing our current schema and listing which composite keys we have. Since we are about removing ones caused by the language columns at #2 already, we should exclude that from this list.

**Comment by IagoSRL** [comment]
For the record: @samwa was already working in a list of CFKs before my previous comment.

**Comment by IagoSRL** [comment]
Adding a comment by @samwa at email about, aside from language/country, there are next composite FK/PKs:
> 1) booking
ALTER TABLE [dbo].[booking]  WITH CHECK ADD  CONSTRAINT [FK__booking__pricingSummary] FOREIGN KEY([PricingSummaryID], [PricingSummaryRevision])
REFERENCES [dbo].[pricingSummary] ([PricingSummaryID], [PricingSummaryRevision])
> 2) pricing Summary
ALTER TABLE [dbo].[pricingSummary]  WITH CHECK ADD  CONSTRAINT [FK_pricingestimate_pricingestimate] FOREIGN KEY([PricingSummaryID], [PricingSummaryRevision])
REFERENCES [dbo].[pricingSummary] ([PricingSummaryID], [PricingSummaryRevision])
> 3) userEarningEntry
ALTER TABLE [dbo].[UserEarningsEntry]  WITH CHECK ADD  CONSTRAINT [FK_UserEarningsEntry_ServiceProfessionalClient] FOREIGN KEY([UserID], [ClientUserID])
REFERENCES [dbo].[ServiceProfessionalClient] ([ServiceProfessionalUserID], [ClientUserID])
> the second one looks like a self referencing comp FK, which can be removed
Not sure about the other 2. I'll do more investigations into how we can modify the generated code to handle these

**Comment by ndarilek** [comment]
Thanks, with the new database schema work, I'm actively making progress on this one. Will ping if I have any issues.

**Comment by ndarilek** [comment]
I think this is mostly done. There are still some composite primary keys in a few many-to-many join tables, but in those instances it makes sense, since the item of interest is the combination of both referenced records rather than a unique new one. Most of what this was involved dropping LanguageID/CountryID as primary keys, then modifying foreign key constraints not to reference them anymore.

The latest work for this is on master, and I'd appreciate a sanity check. I'm next going to merge and continue the work from #2.

Thanks!
